name: itsp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  responsive_framework: ^1.4.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  persistent_bottom_nav_bar_v2: ^4.2.8
  introduction_screen: ^3.1.12
  smooth_page_indicator: ^1.1.0
  icons_launcher: ^2.1.7
  gap: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  infinite_carousel: ^1.1.1
  youtube_player_iframe: ^5.1.1
  map_launcher: ^3.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  font_awesome_flutter: ^10.7.0
  share_plus: ^7.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/fonts/
    - assets/imgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

flutter_native_splash:
  web: false
  background_image: "assets/imgs/splash_background.png"
  image: assets/imgs/logo.png
  android_12:
    background_image: "assets/imgs/splash_background.png"
    image: assets/imgs/logo.png
    icon_background_color: "#081986"
